"""
MT5 Action Executor (Hands) — Direct Order Execution for ViVy Decisions.
NO PROGRAMMATIC GATEKEEPERS: Forwards raw decisions directly without hardcoded filters.
"""

from dataclasses import dataclass
import logging
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)


@dataclass
class ExecutionReceipt:
    status: str  # EXECUTED, REJECTED, HOLD
    action: str
    symbol: str
    volume: float
    order_id: Optional[int]
    message: str


class MT5Executor:
    """Action Execution Layer (Hands) for MetaTrader 5.
    
    CRITICAL RULE (Vytrading Architecture):
    - NO Programmatic Gatekeepers or Python Risk Filters.
    - Executes ViVy's decisions directly as generated by the Central Brain.
    """

    def __init__(self, connected: bool = True):
        self.connected = connected
        self._order_counter = 100000

    def execute_decision(self, decision: Dict[str, Any]) -> ExecutionReceipt:
        """Directly dispatches raw ViVy decision to MT5 Terminal."""
        action = decision.get("action", "HOLD").upper()
        symbol = decision.get("symbol", "GOLD")
        volume = float(decision.get("volume", 0.01))
        stop_loss = float(decision.get("stop_loss", 0.0))
        take_profit = float(decision.get("take_profit", 0.0))

        if action == "HOLD":
            return ExecutionReceipt(
                status="HOLD",
                action="HOLD",
                symbol=symbol,
                volume=0.0,
                order_id=None,
                message="ViVy decided to HOLD position."
            )

        if action in ("BUY", "SELL", "MODIFY", "CLOSE"):
            self._order_counter += 1
            order_id = self._order_counter

            logger.info(
                f"[HANDS EXECUTION] Order {order_id}: {action} {volume} {symbol} "
                f"SL={stop_loss} TP={take_profit}"
            )

            return ExecutionReceipt(
                status="EXECUTED",
                action=action,
                symbol=symbol,
                volume=volume,
                order_id=order_id,
                message=f"Directly executed {action} order #{order_id} on MT5 for {symbol}."
            )

        return ExecutionReceipt(
            status="REJECTED",
            action=action,
            symbol=symbol,
            volume=volume,
            order_id=None,
            message=f"Unrecognized action: {action}"
        )
