"""Knowledge Artifact Writer — V5.0 Sprint 3A.

Hoàn thiện chu trình Active In-Context Epistemic Foraging bằng cách
ghi Knowledge Briefs (4-section format) ra scratchpad/ directory.

Architecture:
    EpistemicGate(NEED_KNOWLEDGE_FORAGING)
        → forager collects raw chunks
        → ContextCacheController.snapshot_context()
        → KnowledgeArtifactWriter.write_brief()  ← THIS MODULE
        → ContextCacheController.purge_raw_chunks()
        → ContextCacheController.load_artifact()
        → EpistemicGate re-assess → EXECUTE_DIRECTLY

Knowledge Brief Format (4 sections mandatory):
    1. Core Mechanics
    2. Hard Invariants
    3. Verified API Signatures
    4. Known Gotchas

Changelog:
    19/09/2026 (Antigravity IDE, Sprint 3A): Initial implementation.
"""

from __future__ import annotations

import hashlib
import logging
import re
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_SCRATCHPAD_DIR = Path("scratchpad")
_KNOWLEDGE_BRIEF_TEMPLATE = """\
# KNOWLEDGE BRIEF: {topic}

**Created:** {timestamp}
**Source:** {source_path}
**Confidence:** {confidence}

## 1. Core Mechanics

{core_mechanics}

## 2. Hard Invariants

{invariants}

## 3. Verified API Signatures

```{lang}
{api_signatures}
```

## 4. Known Gotchas

{gotchas}

---
*Generated by ViVy V5.0 Active In-Context Epistemic Foraging*
"""

_REQUIRED_SECTIONS = [
    "Core Mechanics",
    "Hard Invariants",
    "Verified API Signatures",
    "Known Gotchas",
]


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class KnowledgeBriefContent:
    """Nội dung để điền vào KNOWLEDGE_BRIEF_TEMPLATE.

    Parameters
    ----------
    topic:
        Chủ đề / tên công nghệ (e.g. "CUDA Memory Management").
    source_path:
        Đường dẫn nguồn thô (e.g. "docs/cuda_guide.pdf", "https://...").
    core_mechanics:
        Giải thích cơ chế cốt lõi (bullet points hoặc prose).
    invariants:
        Các ràng buộc kỹ thuật không thể phá vỡ.
    api_signatures:
        Ví dụ code xác thực / API signatures.
    gotchas:
        Các cạm bẫy, bug phổ biến, điều cần tránh.
    lang:
        Ngôn ngữ code cho syntax highlighting (mặc định "python").
    confidence:
        Mức độ tin cậy sau thẩm định (mặc định "VERIFIED").
    metadata:
        Metadata tuỳ chọn.
    """

    topic: str
    source_path: str
    core_mechanics: str
    invariants: str
    api_signatures: str
    gotchas: str
    lang: str = "python"
    confidence: str = "VERIFIED"
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class BriefWriteResult:
    """Kết quả ghi Knowledge Brief."""

    brief_id: str
    file_path: str
    sections_complete: int
    is_complete: bool
    validation_errors: list[str]


# ---------------------------------------------------------------------------
# KnowledgeArtifactWriter
# ---------------------------------------------------------------------------


class KnowledgeArtifactWriter:
    """Viết và kiểm chứng Knowledge Briefs theo chuẩn ViVy V5.0.

    Usage::

        writer = KnowledgeArtifactWriter(scratchpad_dir="scratchpad")
        content = KnowledgeBriefContent(
            topic="FFMPEG Video Slicing",
            source_path="https://ffmpeg.org/docs",
            core_mechanics="Use -ss and -t flags for segment extraction...",
            invariants="Always specify -codec:v copy to avoid re-encoding...",
            api_signatures="ffmpeg -i input.mp4 -ss 00:01:00 -t 30 out.mp4",
            gotchas="Seeking with -ss before -i is faster (keyframe seek)...",
            lang="bash",
        )
        result = writer.write_brief(content)
        assert result.is_complete
    """

    def __init__(self, scratchpad_dir: str | Path = _SCRATCHPAD_DIR) -> None:
        self._scratchpad = Path(scratchpad_dir)
        self._scratchpad.mkdir(parents=True, exist_ok=True)

    def write_brief(self, content: KnowledgeBriefContent) -> BriefWriteResult:
        """Viết Knowledge Brief ra file trong scratchpad directory.

        Parameters
        ----------
        content:
            Nội dung brief đã được thu thập qua Foraging.

        Returns
        -------
        BriefWriteResult
            Kết quả ghi, bao gồm file_path và validation status.
        """
        brief_id = self._generate_id(content.topic)
        timestamp = time.strftime("%Y-%m-%d %H:%M:%S")

        rendered = _KNOWLEDGE_BRIEF_TEMPLATE.format(
            topic=content.topic,
            timestamp=timestamp,
            source_path=content.source_path,
            confidence=content.confidence,
            core_mechanics=content.core_mechanics.strip(),
            invariants=content.invariants.strip(),
            lang=content.lang,
            api_signatures=content.api_signatures.strip(),
            gotchas=content.gotchas.strip(),
        )

        file_path = self._scratchpad / f"knowledge_brief_{brief_id}.md"
        file_path.write_text(rendered, encoding="utf-8")
        logger.info("KnowledgeArtifactWriter: wrote %s", file_path)

        validation_errors = self.validate_completeness(str(file_path))
        sections_complete = len(_REQUIRED_SECTIONS) - len(validation_errors)

        result = BriefWriteResult(
            brief_id=brief_id,
            file_path=str(file_path),
            sections_complete=sections_complete,
            is_complete=len(validation_errors) == 0,
            validation_errors=validation_errors,
        )

        if not result.is_complete:
            logger.warning(
                "KnowledgeArtifactWriter: brief %s is incomplete — %s",
                brief_id,
                validation_errors,
            )

        return result

    def validate_completeness(self, file_path: str) -> list[str]:
        """Kiểm tra Knowledge Brief có đủ 4 sections bắt buộc không.

        Parameters
        ----------
        file_path:
            Đường dẫn file brief để validate.

        Returns
        -------
        list[str]
            Danh sách lỗi validation. Rỗng = brief hoàn chỉnh.
        """
        try:
            content = Path(file_path).read_text(encoding="utf-8")
        except FileNotFoundError:
            return [f"File not found: {file_path}"]

        errors = []
        for section in _REQUIRED_SECTIONS:
            if section not in content:
                errors.append(f"Missing section: {section}")
            else:
                # Find position of this section header and check for content after it
                idx = content.index(section)
                after_header = content[idx + len(section):]
                # Strip the section header line itself
                after_header_stripped = after_header.lstrip(" \t").lstrip("\n").lstrip("\r")
                # Check if there is any non-whitespace content before the next ## heading
                next_heading = after_header_stripped.find("\n##")
                if next_heading == -1:
                    section_body = after_header_stripped
                else:
                    section_body = after_header_stripped[:next_heading]
                if not section_body.strip():
                    errors.append(f"Empty section body: {section}")

        return errors

    def list_briefs(self) -> list[str]:
        """Danh sách tất cả Knowledge Briefs trong scratchpad."""
        return sorted(
            str(p) for p in self._scratchpad.glob("knowledge_brief_*.md")
        )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _generate_id(self, topic: str) -> str:
        """Tạo brief_id từ topic + timestamp (deterministic prefix)."""
        safe_topic = re.sub(r"[^a-zA-Z0-9_]", "_", topic.lower())[:32]
        ts = int(time.time())
        suffix = hashlib.md5(f"{topic}{ts}".encode()).hexdigest()[:6]  # noqa: S324
        return f"{safe_topic}_{suffix}"
